CXX = g++
CXXFLAGS = -Wall

PROGS = atexit cmd-args-env fork0 fork1 fork2 fork3
PROGS += mem mem-fork launch mem2
PROGS += new-delete
PROGS += thread tid

LDFLAGS = -pthread

all:	$(PROGS)

cleanall:
	rm -f $(PROGS)
